// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OMec7y6aOGSTvsQGSYTu1G3-JvVDggU',
    appId: '1:608684701325:web:9864121b8c2e54e066d4c4',
    messagingSenderId: '608684701325',
    projectId: 'my-ecommerce-app-ba18d',
    authDomain: 'my-ecommerce-app-ba18d.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-ba18d.firebasestorage.app',
    measurementId: 'G-7K2847BD9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p-GHk9xucYs8SIjvTP7vDUFwEX3P_-g',
    appId: '1:608684701325:android:7a70023fa78c2d3266d4c4',
    messagingSenderId: '608684701325',
    projectId: 'my-ecommerce-app-ba18d',
    storageBucket: 'my-ecommerce-app-ba18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW4dK4UhhU2RnOJYhB45AhGWnBuBlHO8',
    appId: '1:461613105214:ios:0a6ad6bebe4ae255c6d16f',
    messagingSenderId: '461613105214',
    projectId: 'digital-manga-sshop',
    databaseURL: 'https://digital-manga-sshop-default-rtdb.firebaseio.com',
    storageBucket: 'digital-manga-sshop.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOW4dK4UhhU2RnOJYhB45AhGWnBuBlHO8',
    appId: '1:461613105214:ios:0a6ad6bebe4ae255c6d16f',
    messagingSenderId: '461613105214',
    projectId: 'digital-manga-sshop',
    databaseURL: 'https://digital-manga-sshop-default-rtdb.firebaseio.com',
    storageBucket: 'digital-manga-sshop.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4OMec7y6aOGSTvsQGSYTu1G3-JvVDggU',
    appId: '1:608684701325:web:086fe6c57fa94b2466d4c4',
    messagingSenderId: '608684701325',
    projectId: 'my-ecommerce-app-ba18d',
    authDomain: 'my-ecommerce-app-ba18d.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-ba18d.firebasestorage.app',
    measurementId: 'G-RPC8CWFSER',
  );

}